language: cpp
dist: trusty

# Install dependencies
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y google-mock

# Run cmake to prepare build
before_script:  
    - mkdir build
    - cd build
    - cmake ..

# Build and run tests
script: make && make test 
